name: AndroidBuild
on:
  pull_request :
    branches : [ master ]
  push :
    branches : [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]

    steps:
      - name : Checkout
        uses : actions/checkout@v4.1.4

      - name : Setup java jdk
        uses : actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name : build the apk with gradle
        run : ./gradlew build

      - name : Create a temporary folder
        run : mkdir downloads

      - name : Upload the built apk
        uses : actions/upload-artifact@v4.3.3
        with:
          name: AndroidCICD
          path: downloads/app-debug.apk

      - name : Build the debug apk
        run : ./gradlew assembleDebug

      - name: Upload Apk to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.APP_BUILD_WEBHOOK_URL }}
          CHANNEL_ID : 'D070WLKPN8P'
        run: |
          curl -F file=@downloads/app-debug.apk \
               -F channels=$CHANNEL_ID \
               -F token=$SLACK_WEBHOOK_URL \
               https://slack.com/api/files.upload