name: AndroidBuild
on:
  pull_request :
    branches : [ master ]
  push :
    branches : [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v4.1.4

      - name : Setup java jdk
        uses : actions/setup-java@v4.2.1

      - name : build the apk with gradle
        run : ./gradlew build

      - name : Upload the built apk
        uses : actions/upload-artifact@v4.3.3
        with:
          name: AndroidCICD
          path: app/build/outputs/apk/app-debug.apk