name: AndroidBuild
run-name: Workflow triggered by ${{ github.actor }}
on:
  pull_request :
    branches : [ master ]
  push :
    branches : [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]

    steps:
      - name : Checkout
        uses : actions/checkout@v4.1.4

      - name : Setup java jdk
        uses : actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name : build the apk with gradle
        run : ./gradlew build

      # Extract the Version Code from app level build.gradle and replace period (.) with underscore (_)
      - name: Retrieve Version
        id: android_version
        env:
          APP_VERSION_NAME: ${{ 1.2 }}
        run: |
          echo "VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName) >> $GITHUB_OUTPUT"

      - name: Get version
        run: |
          echo "Third echo MY_App_version_name is ${{ env.VERSION_NAME }}"
          echo "Third2 echo MY_App_version_name is ${{ steps.android_version.env.VERSION_NAME }}"
          echo "Fifth echo MY_App_version_name is ${{ 123 }}"

      - name : Format The Version Code
        run : |
          # Replace (.) with (_) in the version code
          export FORMATTED_VERSION_CODE=$(echo ${{env.APP_VERSION_NAME}} | tr '.' '_')
          echo "Formatted version is ${{ env.APP_VERSION_NAME }}"

      # Concatenate the apk file name with the FORMATTED_VERSION_CODE to make the apk unique
      - name : Concatenate the Version Code with the apk name to get a unique apk name
        run : |
          echo "This is your formatted apk name $FORMATTED_VERSION_CODE and ${{env.version_name}}"
          export APK_NAME="apk-debug-$FORMATTED_VERSION_CODE.apk"

      # Build the apk now, but first create a temporary file to save the built apk to
      - name: Create a temporary folder
        run: mkdir downloads

      - name: Put temporary apk in the created directory
        run: |
          cd downloads       
          echo "This is your formatted apk name $APK_NAME"
          echo '$APK_NAME' > new_apk_name
          cd ..

      - name: Upload the built apk
        uses: actions/upload-artifact@v4.3.3
        with:
          name: AndroidCICD
          path: 'downloads/${{ env.APK_NAME }}'

      - name: Upload Apk to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.APP_BUILD_WEBHOOK_URL }}
          CHANNEL_ID : 'D070WLKPN8P'
          CHANNEL_ID2 : 'ci_cd'
        run: |
          curl -F file=@app/build/outputs/apk/debug/app-debug.apk \
               -F channels=$CHANNEL_ID2 \
               -F token=$SLACK_WEBHOOK_URL \
               https://slack.com/api/files.upload