name: AndroidBuild
on:
  pull_request :
    branches : [ master ]
  push :
    branches : [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]

    steps:
      - name : Checkout
        uses : actions/checkout@v4.1.4

      - name : Setup java jdk
        uses : actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name : build the apk with gradle
        run : ./gradlew build

      - name : Upload the built apk
        uses : actions/upload-artifact@v4.3.3
        with:
          name: AndroidCICD
          path: app/build/outputs/apk/debug/app-debug.apk