name: Scheduled Workflow
run-name: I am using this workflow to learn about how to schedule a workflow to run at a specified time.
on:
  schedule:
    - cron: '9 8 * * 6'
    - cron: '10,15 8 * * 6'

  jobs:
    testing_schedule:
      runs-on: ubuntu-latest

      steps:
        - name: This Step will only run for the first Time Schedule
          if: github.event.schedule != '9 8 * * 6'
          run: echo "This is running for the second scheduled time"

        - name: This runs every time
          run: echo "This runs for all the time"