name: Scheduled Workflow
run-name: I am using this workflow to learn about how to schedule a workflow to run at a specified time.
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '13 10 * * 1,5'  # Mondays and Fridays
    - cron: '13 10 * * 6'

jobs:
  testing_schedule:
    runs-on: ubuntu-latest

    steps:
      - name: This Step will only run for the first Time Schedule
        if: github.event.schedule != '13 10 * * 1,5'
        run: echo "This is running for the second scheduled time"

      - name: This runs every time
        run: echo "This runs for all the time"

      - name: Create Env variables
        env:
          apk_version_name: $(./gradlew printVersionName)
        run: echo 'The Environment variable that i just saved into this step is ${{ env.apk_version_name }}'

      - name: Create Env variables2
        run: |
          output=$(./gradlew printVersionName)
          echo "::set-env name=apk_version_name::$output"
          echo "The value i just saved in the env variable apk_version_name is ${{ env.apk_version_name }}"

      - name: Verifying the ENV variable
        run: echo "Verifying if value is actually saved into the env variable apk_version_name, the saved value is ${{ env.apk_version_name }}"